// ProjectEuler.net


//------------------------------------------------------------------------------
// PROBLEM 1
//------------------------------------------------------------------------------
// If we list all the natural numbers below 10 that are multiples of 3 or 5, we get 3, 5, 6 and 9. The sum of these multiples is 23.

// Find the sum of all the multiples of 3 or 5 below 1000.

var total = 0;

for (i = 1; i < 1000; i++) {
  if (i % 3 === 0 || i % 5 === 0) {
    total += i;
  }
}

console.log("Problem #1: " + total);


//-----------------------------------------------------------------------------
// PROBLEM 2
//-----------------------------------------------------------------------------
// Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

// 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

// By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.

var sum = 0;
var terms = [];

terms[0] = 1;
terms[1] = 2;
terms[2] = 3;

sum = 2;

do {
  terms[0] = terms[1];
  terms[1] = terms[2];
  terms[2] = terms[0] + terms[1];
  if (terms[2] % 2 === 0) {
    sum += terms[2];
  }
} while (terms[2] < 4000000);

console.log("Problem #2: " + sum);


//-----------------------------------------------------------------------------
// PROBLEM 3
//-----------------------------------------------------------------------------
// The prime factors of 13195 are 5, 7, 13 and 29.

// What is the largest prime factor of the number 600851475143 ?

var number = 600851475143;
var divider = 2;
var primes = [];
// var primeTest = 2;
var j = 0;
var status = false;


while (number > 1) {
  console.log(number + ', ' + divider);
  if (number % divider === 0) {
    primes[j] = divider;
    number /= divider;
    j++;
  }
  divider++;
}

console.log(primes);

// do {
//   //console.log(primeTest);
//   status = true;
//   // Find all the primes up to the number / 2
//   for (i = 0; i < primes.length; i++) {
//     if (primeTest % primes[i] === 0) {
//       status = false;
//       primeTest++;
//     }
//   }
//   if (status) {
//     j++;
//     primes[j] = primeTest;
//     console.log(primes[j]);
//   }
// } while (primeTest < (number / 2));

// j = primes.length - 1;

// while (number % primes[j] !== 0) {
//   j--;
// }

// console.log(primes[j]);


  // If a number is divisible by a non-prime, then by definition it is not a prime because it is also divisible by that number's factors


// Test each prime starting with the largest


// function testForPrime(number) {
//   var limit = number / 2;
//   var divider = 2
//   while (divider < limit) {
//     if (number % divider === 0) {
//       return false;
//     } else {
//       return true;
//     }
//   }
// }

// do {
//   console.log(divider);
//   //console.log(number % divider);
//   // check to see if it's a factor
//   if (number % divider === 0) {
//     //console.log(divider + ', ' + number + ', ' + number % divider);
//     var status = testForPrime(divider);
//     if (status) {
//       // console.log('yes');
//       //console.log(divider);
//     } else {
//       divider--;

//       //console.log('minus');
//     }
//   } else {
//     var result = Math.floor(number / divider);
//     console.log(result);
//     divider = (number / result);
//   }
// } while (divider > 1 && (status === false));


//-----------------------------------------------------------------------------
// PROBLEM 4
//-----------------------------------------------------------------------------
// A palindromic number reads the same both ways. The largest palindrome made from the product of two 2-digit numbers is 9009 = 91 × 99.

// Find the largest palindrome made from the product of two 3-digit numbers.


//-----------------------------------------------------------------------------
// PROBLEM 5
//-----------------------------------------------------------------------------
// 2520 is the smallest number that can be divided by each of the numbers from 1 to 10 without any remainder.

// What is the smallest positive number that is evenly divisible by all of the numbers from 1 to 20?